/**:
  ros__parameters:
    # Parameters that you want to evaluate
    stddev_vx: 0.11291
    stddev_wz: 0.00284
    coef_vx: 1.0087
    bias_wz: 2e-05

    # Dead Reckoning configuration
    wait_duration: 2.0 # [s]
    wait_scale: 1.3
