parameter_estimator:
  ros__parameters:
    # Parameters that you want to evaluate
    stddev_vx: 0.3 # [m/s]
    stddev_wz: 0.02 # [rad/s]
    coef_vx: 1.0 # [m/s]
    bias_wz: 0.0 # [-]

    # Dead Reckoning configuration
    period: 10.0 # [s]
    cut: 9.0 # [s]
